---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-ai-detective-config
  namespace: k8s-ai-detective
data:
  config.yml: |
    ---
    include_alert_groups:
      - kubernetes-apps
    include_namespace:
      - monitoring
