apiVersion: v1
kind: Secret
metadata:
  name: k8s-ai-detective-secrets
  namespace: k8s-ai-detective
type: Opaque
data:
  API_KEY: eW91ci1hcGkta2V5
  SLACK_BOT_TOKEN: eW91ci1zbGFjay1ib3QtdG9rZW4=
  SLACK_CHANNEL_ID: eW91ci1zbGFjay1jaGFubmVsLWlk
